FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IG9wZW5zaGlmdC1jbG91ZC1ldmVudC1zb3VyY2UtYXBiCmRlc2Ny\
aXB0aW9uOiBUaGlzIGlzIGEgc2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5p\
dApiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1l\
OiBvcGVuc2hpZnQtY2xvdWQtZXZlbnQtc291cmNlCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAog\
ICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgb3BlbnNoaWZ0LWNsb3Vk\
LWV2ZW50LXNvdXJjZS1hcGIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFy\
YW1ldGVyczoKICAgIC0gbmFtZTogYWRtaW5fdXNlcgogICAgICB0aXRsZTogT3BlbnNoaWZ0IEFk\
bWluIFVzZXIKICAgICAgdHlwZTogc3RyaW5nCiAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAtIG5h\
bWU6IGFkbWluX3Bhc3N3b3JkCiAgICAgIHRpdGxlOiBPcGVuc2hpZnQgQWRtaW4gUGFzc3dvcmQK\
ICAgICAgdHlwZTogc3RyaW5nCiAgICAgIGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAgcmVx\
dWlyZWQ6IHRydWUK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
