FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IG9wZW5zaGlmdC1jbG91ZC1ldmVudC1tb25pdG9yLWFwYgpkZXNj\
cmlwdGlvbjogTW9uaXRvciB0aGUgb3BlbnNoaWZ0IHBsYXRmb3JtIGFuZCBlbWl0IENsb3VkIEV2\
ZW50cwpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlO\
YW1lOiBPcGVuc2hpZnQgQ2xvdWQgRXZlbnQgTW9uaXRvcgogIGltYWdlVXJsOiAiaHR0cHM6Ly9h\
dmF0YXJzMC5naXRodWJ1c2VyY29udGVudC5jb20vdS83OTIzMzc/cz0yMDAmdj00IgpwbGFuczoK\
ICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBUaGlzIGRlcGxveXMgdGhlIEt1YmVy\
bmV0ZXMgQ2xvdWQgRXZlbnQgTW9uaXRvcgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9\
CiAgICBwYXJhbWV0ZXJzOgogICAgLSBuYW1lOiBhZG1pbl91c2VyCiAgICAgIHRpdGxlOiBPcGVu\
c2hpZnQgQWRtaW4gVXNlcgogICAgICB0eXBlOiBzdHJpbmcKICAgICAgcmVxdWlyZWQ6IHRydWUK\
ICAgIC0gbmFtZTogYWRtaW5fcGFzc3dvcmQKICAgICAgdGl0bGU6IE9wZW5zaGlmdCBBZG1pbiBQ\
YXNzd29yZAogICAgICB0eXBlOiBzdHJpbmcKICAgICAgZGlzcGxheV90eXBlOiBwYXNzd29yZAog\
ICAgICByZXF1aXJlZDogdHJ1ZQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
